<a href="https://colab.research.google.com/github/igoormaurilio/TerraSignal/blob/main/databricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto Interdisciplinar - databricks "Terra Signal"

In [6]:
import pandas as pd

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
df_bruto = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DataBricks/history.csv")

In [11]:
df_bruto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5634 non-null   object
 1   gender            5634 non-null   object
 2   SeniorCitizen     5634 non-null   int64
 3   Partner           5634 non-null   object
 4   Dependents        5634 non-null   object
 5   tenure            5634 non-null   object
 6   PhoneService      5634 non-null   object
 7   MultipleLines     5634 non-null   object
 8   InternetService   5634 non-null   object
 9   OnlineSecurity    5634 non-null   object
 10  OnlineBackup      5634 non-null   object
 11  DeviceProtection  5634 non-null   object
 12  TechSupport       5634 non-null   object
 13  StreamingTV       5634 non-null   object
 14  StreamingMovies   5634 non-null   object
 15  Contract          5634 non-null   object
 16  PaperlessBilling  5634 non-null   object
 17  PaymentMethod     5634 non-null   object
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   object
 21  CustomerFeedback  5634 non-null   object
 22  MonthlyIncome     5634 non-null   int64
dtypes: float64(2), int64(2), object(19)
memory usage: 1012.5+ KB

**tradução dessas colunas**
- Contract - Contrato / Tipo de contrato do cliente
- PaperlessBilling - Faturamento sem papel /Se recebe a fatura digitalmente
- PaymentMethod - Método de pagamento / Forma utilizada para pagamento
- MonthlyCharges - Cobranças mensais / Valor cobrado mensalmente
- TotalCharges - Cobranças totais	/ Valor total cobrado do cliente
- Churn - Situação de Cancelamento / Indica se o cliente cancelou o serviço
- CustomerFeedback - Feedback do cliente / Avaliação ou opinião fornecida pelo cliente
- MonthlyIncome - Renda mensal / Renda mensal do cliente

In [12]:
df_bruto.head(30)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691
5,6797-LNAQX,Male,0,Yes,Yes,70,Yes,Yes,Fiber optic,No,...,Yes,Yes,Two year,No,Bank transfer (automatic),98.30,6859.50,Yes,I have been a customer with this company for 7...,5487
6,3050-GBUSH,Female,0,No,No,3,no,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Credit card (automatic),34.80,113.95,No,I have been a customer with this DSL internet ...,6382
7,8020-BWHYL,Female,1,No,No,15,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Credit card (automatic),75.30,NaN,Yes,I recently canceled my service with this provi...,353
8,6752-APNJL,Male,0,Yes,Yes,42,Yes,No,DSL,Yes,...,No,No,Month-to-month,No,Mailed check,54.50,2301.15,No,I have been a customer with this company for 4...,2436
9,1760-CAZHT,Male,0,No,Yes,25,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,No,Mailed check,20.80,460.20,No,I have been a customer with this company for 2...,7049
10,3070-FNFZQ,Female,0,Yes,Yes,23,Yes,No,No,No internet service,...,No internet service,No internet service,Two year,No,Bank transfer (automatic),20.40,478.75,No,I have been a customer with this company for 2...,4625
11,4452-QIIEB,Male,0,No,No,7,Yes,No,DSL,No,...,No,No,Month-to-month,No,Mailed check,43.90,278.40,No,I have been a customer with this DSL internet ...,1204
12,7767-UXAGJ,Male,0,No,No,1,Yes,Yes,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,50.45,50.45,Yes,I recently signed up for DSL internet service ...,5388
13,9793-WECQC,Male,0,No,No,23,Yes,No,Fiber optic,No,...,Yes,Yes,Month-to-month,No,Mailed check,95.30,2192.90,No,I have been a customer with this company for a...,6643
14,7029-IJEJK,Female,0,No,No,54,No,No phone service,DSL,Yes,...,No,Yes,One year,No,Bank transfer (automatic),44.10,2369.70,No,I have been a loyal customer of this DSL inter...,5176
15,5419-JKZNQ,Male,1,Yes,No,30,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,No,Mailed check,77.90,2351.45,No,I have been a customer with this internet serv...,3934
16,3351-NQLDI,Female,0,Yes,Yes,67,Yes,Yes,Fiber optic,Yes,...,No,Yes,One year,Yes,Credit card (automatic),94.35,6341.45,Yes,I have been a customer with this company for 6...,2645
17,1335-HQMKX,Female,0,Yes,No,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,Yes,Electronic check,101.35,7323.15,No,I have been a loyal customer of this internet ...,419
18,4702-IOQDC,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.10,70.10,Yes,I recently signed up for the fiber optic inter...,2000
19,2043-WVTQJ,Male,0,Yes,No,1,Yes,No,DSL,Yes,...,No,No,Month-to-month,No,Mailed check,55.70,55.70,No,I have been a customer for just over a month n...,2467
20,5320-BRKGK,Female,0,Yes,Yes,58,Yes,Yes,DSL,Yes,...,Yes,No,Two year,No,Mailed check,75.80,4415.75,No,I have been a customer with this company for o...,6609
21,5945-AZYHT,Male,0,Yes,No,71,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,One year,Yes,Electronic check,109.60,7854.15,No,I have been a loyal customer of this company f...,6591
22,6653-CBBOM,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,70.30,Yes,I recently signed up for fiber optic internet ...,4055
23,7995-ZHHNZ,Male,0,Yes,No,42,Yes,Yes,DSL,Yes,...,No,No,One year,No,Credit card (automatic),56.10,2386.85,No,I have been a customer with this internet serv...,1556
24,8267-ZNYVZ,Female,0,Yes,No,33,Yes,No,Fiber optic,Yes,...,Yes,Yes,One year,Yes,Electronic check,103.75,3361.05,Yes,I was initially satisfied with my fiber optic ...,6879
25,0093-EXYQL,Female,1,No,No,40,Yes,No,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,91.55,3673.60,No,I have been a customer with this company for o...,1899
26,7717-BICXI,Male,0,Yes,Yes,60,Yes,No,No,No internet service,...,No internet service,No internet service,Two year,No,Mailed check,20.55,1205.05,No,I have been a customer with this company for 5...,1028
27,2323-ARSVR,Male,0,Yes,No,67,Yes,No,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Electronic check,111.05,7321.05,No,"""I have been a loyal customer with this compan...",9136
28,5281-BUZGT,Male,1,No,No,36,Yes,Yes,Fiber optic,Yes,...,Yes,No,Month-to-month,Yes,Electronic check,90.85,3186.70,Yes,I have been a customer with this company for 3...,9952
29,1930-WNXSB,Male,0,Yes,Yes,58,Yes,No,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,92.85,5305.05,No,I have been a customer with this company for a...,6135

In [14]:
df_bruto.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
5629,8909-BOLNL,Male,0,No,No,3,Yes,No,No,No internet service,...,No internet service,No internet service,One year,No,Mailed check,21.20,52.05,No,I have been a customer with this company for 3...,8354
5630,2832-KJCRD,Female,0,No,No,38,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,103.65,3988.50,No,I have been a customer with this company for 3...,9308
5631,7975-JMZNT,Male,0,Yes,No,66,Yes,Yes,DSL,Yes,...,Yes,Yes,Two year,No,Bank transfer (automatic),91.70,6075.90,No,I have been a customer with this DSL internet ...,2113
5632,4250-ZBWLV,Male,0,No,No,68,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Electronic check,108.45,7176.55,Yes,I have been a customer with this company for o...,3904
5633,3915-ODIYG,Male,1,No,No,60,Yes,Yes,DSL,Yes,...,No,Yes,One year,Yes,Electronic check,71.75,4374.55,No,I have been a loyal customer of this internet ...,3016

In [15]:
df_bruto.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure               object
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
CustomerFeedback     object
MonthlyIncome         int64
dtype: object

In [17]:
df_bruto.isnull().sum()

customerID            0
gender                0
SeniorCitizen         0
Partner               0
Dependents            0
tenure                0
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection      0
TechSupport           0
StreamingTV           0
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges        278
Churn                 0
CustomerFeedback      0
MonthlyIncome         0
dtype: int64

In [18]:
df_bruto.duplicated().sum()

np.int64(0)