<center><h1><strong>Ingestão de Dados - <span style="color: #CD7F32;">Camada Bronze</span></strong></h1></center>

## 1. Instalação e importação das bibliotecas necessárias

In [2]:
# %pip install pandas

In [3]:
import pandas as pd

## 2. Carregando os dados

In [4]:
df_bronze = pd.read_csv('../data/raw/history.csv')

### 3 Inspeção inicial dos dados

In [5]:
def analisar_dataframe(df, nome_tabela):
    print(f"{"="*20} {nome_tabela.upper()} {"="*20}")
    print(f"Linhas: {df.shape[0]}\nColunas: {df.shape[1]}")
    display(f"Valores duplicados: {df.duplicated().sum()}")
    print(f"Valores nulos:")
    display(df.isna().sum())
    display(df.head(10))
    display(df.tail(10))
    display(df.sample(10))
    display(df.info())

In [6]:
analisar_dataframe(df_bronze, "Carteira de clientes - Terra Signal")

==================== CARTEIRA DE CLIENTES - TERRA SIGNAL ====================
Linhas: 5634
Colunas: 23

'Valores duplicados: 0'

Valores nulos:

customerID            0
gender                0
SeniorCitizen         0
Partner               0
Dependents            0
tenure                0
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection      0
TechSupport           0
StreamingTV           0
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges        278
Churn                 0
CustomerFeedback      0
MonthlyIncome         0
dtype: int64

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691
5,6797-LNAQX,Male,0,Yes,Yes,70,Yes,Yes,Fiber optic,No,...,Yes,Yes,Two year,No,Bank transfer (automatic),98.30,6859.50,Yes,I have been a customer with this company for 7...,5487
6,3050-GBUSH,Female,0,No,No,3,no,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Credit card (automatic),34.80,113.95,No,I have been a customer with this DSL internet ...,6382
7,8020-BWHYL,Female,1,No,No,15,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Credit card (automatic),75.30,NaN,Yes,I recently canceled my service with this provi...,353
8,6752-APNJL,Male,0,Yes,Yes,42,Yes,No,DSL,Yes,...,No,No,Month-to-month,No,Mailed check,54.50,2301.15,No,I have been a customer with this company for 4...,2436
9,1760-CAZHT,Male,0,No,Yes,25,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,No,Mailed check,20.80,460.20,No,I have been a customer with this company for 2...,7049

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
5624,8869-LIHMK,Female,0,No,No,64,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),115.10,7334.05,No,I have been a loyal customer of this company f...,5342
5625,0932-YIXYU,Female,0,No,No,47,yes,No,No,No internet service,...,No internet service,No internet service,Two year,No,Credit card (automatic),20.25,1029.80,No,I have been a customer with this company for a...,9229
5626,3569-EDBPQ,Female,0,No,No,24,Yes,Yes,Fiber optic,Yes,...,No,No,Month-to-month,Yes,Electronic check,84.35,1938.05,No,I have been a customer with this fiber optic i...,7165
5627,8645-KOMJQ,Male,0,Yes,Yes,69,Yes,Yes,DSL,No,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),81.95,5601.40,No,I have been a loyal customer with this company...,411
5628,0786-IVLAW,Female,1,No,No,66,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Bank transfer (automatic),108.10,7238.60,No,I have been a customer with this company for 6...,5113
5629,8909-BOLNL,Male,0,No,No,3,Yes,No,No,No internet service,...,No internet service,No internet service,One year,No,Mailed check,21.20,52.05,No,I have been a customer with this company for 3...,8354
5630,2832-KJCRD,Female,0,No,No,38,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,103.65,3988.50,No,I have been a customer with this company for 3...,9308
5631,7975-JMZNT,Male,0,Yes,No,66,Yes,Yes,DSL,Yes,...,Yes,Yes,Two year,No,Bank transfer (automatic),91.70,6075.90,No,I have been a customer with this DSL internet ...,2113
5632,4250-ZBWLV,Male,0,No,No,68,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Electronic check,108.45,7176.55,Yes,I have been a customer with this company for o...,3904
5633,3915-ODIYG,Male,1,No,No,60,Yes,Yes,DSL,Yes,...,No,Yes,One year,Yes,Electronic check,71.75,4374.55,No,I have been a loyal customer of this internet ...,3016

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
1708,9894-EZEWG,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Credit card (automatic),74.30,74.30,Yes,I recently switched to this internet service p...,7257
1735,1666-JZPZT,Male,0,No,No,27,Yes,Yes,DSL,No,...,No,No,Month-to-month,No,Mailed check,49.00,1291.35,No,I have been a customer with this company for 2...,8973
5359,7993-NQLJE,Male,0,Yes,Yes,15,Yes,No,Fiber optic,Yes,...,No,No,Month-to-month,No,Mailed check,75.10,1151.55,No,I have been a customer of this fiber optic int...,1388
1996,5378-IKEEG,Female,0,No,No,1,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.75,35.75,Yes,I recently signed up for DSL internet service ...,7652
3041,4816-LXZYW,Female,0,No,No,23,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,79.15,1676.95,Yes,I have been a customer with this company for a...,9232
3482,0067-DKWBL,Male,1,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Electronic check,49.25,91.10,Yes,I recently switched to this internet service p...,2000
4433,1699-UOTXU,Male,0,No,No,60,Yes,No,DSL,Yes,...,No,No,Two year,No,Electronic check,61.40,3638.25,No,I have been a loyal customer for 5 years now a...,9697
4666,7636-XUHWW,Male,0,No,No,2,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,Yes,Credit card (automatic),19.90,33.70,No,I have been a customer with this company for 2...,1109
507,3197-ARFOY,Female,1,No,No,19,Yes,No,Fiber optic,Yes,...,Yes,Yes,Month-to-month,Yes,Mailed check,105.00,2007.25,No,I have been a customer with this company for a...,3105
4598,1898-JSNDC,Female,0,No,No,39,Yes,No,DSL,No,...,Yes,No,One year,Yes,Credit card (automatic),58.60,2224.50,No,I have been a customer with this internet serv...,3096

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5634 non-null   str
 1   gender            5634 non-null   str
 2   SeniorCitizen     5634 non-null   int64
 3   Partner           5634 non-null   str
 4   Dependents        5634 non-null   str
 5   tenure            5634 non-null   str
 6   PhoneService      5634 non-null   str
 7   MultipleLines     5634 non-null   str
 8   InternetService   5634 non-null   str
 9   OnlineSecurity    5634 non-null   str
 10  OnlineBackup      5634 non-null   str
 11  DeviceProtection  5634 non-null   str
 12  TechSupport       5634 non-null   str
 13  StreamingTV       5634 non-null   str
 14  StreamingMovies   5634 non-null   str
 15  Contract          5634 non-null   str
 16  PaperlessBilling  5634 non-null   str
 17  PaymentMethod     5634 non-null   str
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   str
 21  CustomerFeedback  5634 non-null   str
 22  MonthlyIncome     5634 non-null   int64
dtypes: float64(2), int64(2), str(19)
memory usage: 1012.5 KB

None