<center><h1><strong>Tratamento dos Dados - <span style="color: #bcc6cc;">Camada Silver</span></strong></h1></center>

## 1. Instalação e importação das bibliotecas necessárias

In [162]:
# %pip install pandas numpy

In [163]:
import pandas as pd
import numpy as np

## 2. Carregando os dados

In [164]:
df_bruto = pd.read_csv('../data/raw/history.csv')

## 3. Entendimento das variáveis e estrutura do DataFrame

![Dicionário de Dados](../dicionario_dados.png)

- **customerID** - ID do cliente / Identificador único do cliente
- **gender** - Gênero / Gênero do cliente
- **SeniorCitizen** - Cidadão idoso / Indica se o cliente é idoso
- **Partner** - Parceiro(a) / Indica se o cliente possui cônjuge ou parceiro(a)
- **Dependents** - Dependentes / Indica se o cliente possui dependentes
- **tenure** - Tempo de permanência / Quantidade de meses que o cliente está na empresa
- **PhoneService** - Serviço telefônico / Indica se o cliente possui serviço de telefone
- **MultipleLines** - Múltiplas linhas / Indica se o cliente possui mais de uma linha telefônica
- **InternetService** - Serviço de internet / Tipo de serviço de internet contratado pelo cliente
- **OnlineSecurity** - Segurança online / Indica se o cliente possui serviço de segurança online
- **OnlineBackup** - Backup online / Indica se o cliente possui serviço de backup online
- **DeviceProtection** - Proteção de dispositivos / Indica se o cliente possui serviço de proteção para dispositivos
- **TechSupport** - Suporte técnico / Indica se o cliente possui serviço de suporte técnico
- **StreamingTV** - TV por streaming / Indica se o cliente possui serviço de televisão por streaming
- **StreamingMovies** - Filmes por streaming / Indica se o cliente possui serviço de filmes por streaming
- **Contract** - Contrato / Tipo de contrato do cliente
- **PaperlessBilling** - Faturamento sem papel /Se recebe a fatura digitalmente
- **PaymentMethod** - Método de pagamento / Forma utilizada para pagamento
- **MonthlyCharges** - Cobranças mensais / Valor cobrado mensalmente
- **TotalCharges** - Cobranças totais	/ Valor total cobrado do cliente
- **Churn** - Situação de Cancelamento / Indica se o cliente cancelou o serviço

## 4. Inspeção inicial dos dados

In [165]:
def analisar_dataframe(df, nome_tabela):
    print(f"{"="*20} {nome_tabela.upper()} {"="*20}")
    print(f"Linhas: {df.shape[0]}\nColunas: {df.shape[1]}")
    display(f"Valores duplicados: {df.duplicated().sum()}")
    print(f"Valores nulos:")
    display(df.isna().sum())
    display(df.head(10))
    display(df.tail(10))
    display(df.sample(10))
    display(df.info())

In [166]:
analisar_dataframe(df_bruto, "Carteira de clientes - Terra Signal")

==================== CARTEIRA DE CLIENTES - TERRA SIGNAL ====================
Linhas: 5634
Colunas: 23

'Valores duplicados: 0'

Valores nulos:

customerID            0
gender                0
SeniorCitizen         0
Partner               0
Dependents            0
tenure                0
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection      0
TechSupport           0
StreamingTV           0
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges        278
Churn                 0
CustomerFeedback      0
MonthlyIncome         0
dtype: int64

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691
5,6797-LNAQX,Male,0,Yes,Yes,70,Yes,Yes,Fiber optic,No,...,Yes,Yes,Two year,No,Bank transfer (automatic),98.30,6859.50,Yes,I have been a customer with this company for 7...,5487
6,3050-GBUSH,Female,0,No,No,3,no,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Credit card (automatic),34.80,113.95,No,I have been a customer with this DSL internet ...,6382
7,8020-BWHYL,Female,1,No,No,15,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Credit card (automatic),75.30,NaN,Yes,I recently canceled my service with this provi...,353
8,6752-APNJL,Male,0,Yes,Yes,42,Yes,No,DSL,Yes,...,No,No,Month-to-month,No,Mailed check,54.50,2301.15,No,I have been a customer with this company for 4...,2436
9,1760-CAZHT,Male,0,No,Yes,25,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,No,Mailed check,20.80,460.20,No,I have been a customer with this company for 2...,7049

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
5624,8869-LIHMK,Female,0,No,No,64,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),115.10,7334.05,No,I have been a loyal customer of this company f...,5342
5625,0932-YIXYU,Female,0,No,No,47,yes,No,No,No internet service,...,No internet service,No internet service,Two year,No,Credit card (automatic),20.25,1029.80,No,I have been a customer with this company for a...,9229
5626,3569-EDBPQ,Female,0,No,No,24,Yes,Yes,Fiber optic,Yes,...,No,No,Month-to-month,Yes,Electronic check,84.35,1938.05,No,I have been a customer with this fiber optic i...,7165
5627,8645-KOMJQ,Male,0,Yes,Yes,69,Yes,Yes,DSL,No,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),81.95,5601.40,No,I have been a loyal customer with this company...,411
5628,0786-IVLAW,Female,1,No,No,66,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Bank transfer (automatic),108.10,7238.60,No,I have been a customer with this company for 6...,5113
5629,8909-BOLNL,Male,0,No,No,3,Yes,No,No,No internet service,...,No internet service,No internet service,One year,No,Mailed check,21.20,52.05,No,I have been a customer with this company for 3...,8354
5630,2832-KJCRD,Female,0,No,No,38,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,103.65,3988.50,No,I have been a customer with this company for 3...,9308
5631,7975-JMZNT,Male,0,Yes,No,66,Yes,Yes,DSL,Yes,...,Yes,Yes,Two year,No,Bank transfer (automatic),91.70,6075.90,No,I have been a customer with this DSL internet ...,2113
5632,4250-ZBWLV,Male,0,No,No,68,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Electronic check,108.45,7176.55,Yes,I have been a customer with this company for o...,3904
5633,3915-ODIYG,Male,1,No,No,60,Yes,Yes,DSL,Yes,...,No,Yes,One year,Yes,Electronic check,71.75,4374.55,No,I have been a loyal customer of this internet ...,3016

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
5206,3165-HDOEW,Male,0,Yes,Yes,1,Yes,No,DSL,No,...,No,No,Month-to-month,Yes,Mailed check,45.85,45.85,Yes,I recently signed up for DSL internet with thi...,3738
197,7396-VJUZB,Male,0,Yes,Yes,4,Yes,No,DSL,No,...,No,No,Month-to-month,No,Mailed check,45.25,155.35,No,I have been a customer with this internet serv...,8214
1244,7932-WPTDS,Female,1,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,24.80,24.80,Yes,I recently signed up for DSL internet service ...,1049
2911,8949-JTMAY,Female,0,No,No,29,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Credit card (automatic),98.60,2933.20,Yes,I have been a customer for almost 2 and a half...,1760
4882,6518-PPLMZ,Male,0,Yes,Yes,53,Yes,No,No,No internet service,...,No internet service,No internet service,Two year,Yes,Mailed check,19.40,1110.35,No,I have been a loyal customer for over four yea...,5246
1818,6821-JPCDC,Female,0,Yes,No,48,Yes,No,Fiber optic,No,...,Yes,Yes,One year,Yes,Electronic check,97.05,4692.95,No,I have been a customer with this company for 4...,9839
5617,0822-GAVAP,Female,0,No,No,2,No,No phone service,DSL,No,...,No,Yes,Month-to-month,Yes,Electronic check,34.70,62.25,Yes,I recently signed up for DSL internet service ...,9320
5392,6464-KEXXH,Male,0,No,No,8,no,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Credit card (automatic),25.25,186.30,No,I have been a customer with this DSL internet ...,3397
3393,1114-CENIM,Male,0,No,Yes,54,Yes,Yes,DSL,No,...,No,No,Month-to-month,Yes,Credit card (automatic),55.00,3092.65,Yes,I have been a customer with this company for o...,5338
2736,9770-LXDBK,Female,0,No,No,3,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,No,Mailed check,20.40,63.15,No,I have been a customer with this company for 3...,8278

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5634 non-null   str
 1   gender            5634 non-null   str
 2   SeniorCitizen     5634 non-null   int64
 3   Partner           5634 non-null   str
 4   Dependents        5634 non-null   str
 5   tenure            5634 non-null   str
 6   PhoneService      5634 non-null   str
 7   MultipleLines     5634 non-null   str
 8   InternetService   5634 non-null   str
 9   OnlineSecurity    5634 non-null   str
 10  OnlineBackup      5634 non-null   str
 11  DeviceProtection  5634 non-null   str
 12  TechSupport       5634 non-null   str
 13  StreamingTV       5634 non-null   str
 14  StreamingMovies   5634 non-null   str
 15  Contract          5634 non-null   str
 16  PaperlessBilling  5634 non-null   str
 17  PaymentMethod     5634 non-null   str
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   str
 21  CustomerFeedback  5634 non-null   str
 22  MonthlyIncome     5634 non-null   int64
dtypes: float64(2), int64(2), str(19)
memory usage: 1012.5 KB

None

## 5. Tratamento de valores `unknown` na coluna **ternure**

### 5.1. Identificando os valores

In [167]:
quantidade_unknown = df_bruto["tenure"].astype("string").str.strip().str.lower().eq("unknown").sum()
print(f"Quantidade unknown: {quantidade_unknown} valores")

Quantidade unknown: 19 valores

In [168]:
df_bruto.loc[
    df_bruto["tenure"].astype("string").str.strip().str.lower() == "unknown"
]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
1059,7301-ABVAD,Female,0,No,No,unknown,Yes,Yes,DSL,No,...,Yes,Yes,Two year,No,Bank transfer (automatic),86.60,6350.50,No,I have been a customer with this company for 6...,3093
1097,9651-GTSAQ,Female,0,Yes,No,unknown,Yes,No,Fiber optic,Yes,...,Yes,Yes,One year,Yes,Bank transfer (automatic),106.10,NaN,Yes,I have been a customer with this company for o...,4702
1791,0135-NMXAP,Female,0,No,No,unknown,Yes,Yes,Fiber optic,No,...,Yes,No,Month-to-month,Yes,Bank transfer (automatic),89.75,1052.40,Yes,I recently cancelled my service with this comp...,7709
1984,3892-NXAZG,Male,0,Yes,Yes,unknown,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Credit card (automatic),114.05,8289.20,No,I have been a customer with this company for 6...,4415
2361,3934-HXCFZ,Male,0,Yes,No,unknown,Yes,Yes,Fiber optic,Yes,...,Yes,No,Month-to-month,Yes,Electronic check,99.25,2186.40,Yes,I have been a customer of this fiber optic int...,9165
2372,1622-HSHSF,Female,0,No,No,unknown,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,Yes,Mailed check,19.55,19.55,No,I have only been a customer with this company ...,4751
2641,6907-NZZIJ,Female,0,No,No,unknown,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,99.15,3615.60,Yes,I have been a customer with this company for 3...,4701
2896,6023-GSSXW,Female,0,Yes,No,unknown,Yes,No,DSL,No,...,No,Yes,Two year,Yes,Credit card (automatic),61.45,4131.20,No,I have been a customer with this company for a...,2494
2936,5688-KZTSN,Male,0,Yes,Yes,unknown,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,Yes,Electronic check,20.00,288.05,Yes,I recently cancelled my service with this prov...,4749
2959,7694-VLBWQ,Male,0,Yes,No,unknown,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Electronic check,104.10,7040.85,Yes,I have been a customer with this company for o...,8867
3153,1619-YWUBB,Female,0,Yes,No,unknown,Yes,Yes,No,No internet service,...,No internet service,No internet service,Two year,Yes,Credit card (automatic),24.95,1614.90,No,I have been a customer with this company for o...,8009
3300,9575-IWCAZ,Male,0,Yes,No,unknown,Yes,Yes,No,No internet service,...,No internet service,No internet service,One year,No,Mailed check,25.10,171.00,No,I have been a customer with this company for 6...,752
3388,4702-HDRKD,Male,0,No,No,unknown,No,No phone service,DSL,Yes,...,Yes,No,One year,Yes,Bank transfer (automatic),49.35,3321.35,No,I have been a loyal customer of this DSL inter...,198
3476,6469-QJKZW,Female,0,Yes,No,unknown,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,No,Electronic check,20.15,91.40,No,I have been a customer with this company for 4...,1306
3515,2672-HUYVI,Female,0,No,No,unknown,Yes,No,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,91.10,455.30,Yes,I recently canceled my service after being a c...,5701
3837,3274-NSDWE,Female,0,No,No,unknown,Yes,No,No,No internet service,...,No internet service,No internet service,Two year,No,Credit card (automatic),19.60,1441.65,No,I have been a loyal customer with this company...,3753
4875,3348-CFRNX,Female,0,Yes,No,unknown,Yes,No,Fiber optic,Yes,...,Yes,Yes,Month-to-month,Yes,Mailed check,92.35,2602.90,Yes,I recently made the difficult decision to canc...,1437
5324,6614-VBEGU,Female,0,Yes,No,unknown,Yes,No,DSL,No,...,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),69.45,1614.05,No,I have been a customer with this internet prov...,3688
5328,1293-BSEUN,Female,0,Yes,Yes,unknown,Yes,No,No,No internet service,...,No internet service,No internet service,Two year,Yes,Mailed check,20.70,1482.30,No,I have been a customer with this company for 6...,3396

### 5.2. Identificação manual dos valores `unknown` pela coluna **CostumerFeedback**

A coluna CostumerFeedback, as vezes indica quanto tempo o cliente está, ou esteve, vinculado a empresa.

In [169]:
mascara = (
    df_bruto["tenure"]
    .astype("string")
    .str.strip()
    .str.lower()
    .eq("unknown")
)

for indice, linha in df_bruto.loc[mascara].iterrows():
    print(f"Índice: {indice}")
    print(f"Cliente: {linha['customerID']}")
    print(f"Feedback: {linha['CustomerFeedback']}")
    print("-" * 80)

Índice: 1059
Cliente: 7301-ABVAD
Feedback: I have been a customer with this company for 6 years now and I have been very satisfied with the service. The DSL internet service has been reliable and the monthly charges are reasonable at $86.6. I appreciate the convenience of automatic bank transfer for payments. Overall, I have had no issues with the service and I have no plans to churn.
--------------------------------------------------------------------------------
Índice: 1097
Cliente: 9651-GTSAQ
Feedback: I have been a customer with this company for over four years now, using their fiber optic internet service. The service itself has been reliable and fast, which is great for my needs. However, I recently decided to churn because I found a better deal with another provider. The monthly charges of $106.1 were a bit on the higher side, and I felt like I could save some money by switching. Overall, I have had a positive experience with this company, but ultimately decided to move on for financial reasons.
--------------------------------------------------------------------------------
Índice: 1791
Cliente: 0135-NMXAP
Feedback: I recently cancelled my service with this company after being a customer for 12 months. I was on a month-to-month contract with monthly charges of $89.75 for fiber optic internet service. I opted for bank transfer for automatic payments. While the internet service itself was reliable and fast, I ultimately decided to switch providers due to finding a better deal elsewhere. The cancellation process was smooth and hassle-free, but I would have appreciated more competitive pricing options to possibly keep me as a customer.
--------------------------------------------------------------------------------
Índice: 1984
Cliente: 3892-NXAZG
Feedback: I have been a customer with this company for 6 years now and have been very satisfied with their fiber optic internet service. The automatic credit card payment option has made it easy to keep up with my monthly charges of $114.05. I have not experienced any issues with my service and have not had any reason to consider switching providers. Overall, I am happy with my experience and would recommend this company to others.
--------------------------------------------------------------------------------
Índice: 2361
Cliente: 3934-HXCFZ
Feedback: I have been a customer of this fiber optic internet service for nearly two years now, opting for the month-to-month contract at a monthly charge of $99.25. While the service itself has been reliable and the speeds are fast, I recently made the decision to churn and switch to a different provider due to the increasing monthly charges. I found a better deal elsewhere and felt that it was time for a change. Overall, I was satisfied with the service during my time as a customer, but the cost became a deciding factor in my decision to leave.
--------------------------------------------------------------------------------
Índice: 2372
Cliente: 1622-HSHSF
Feedback: I have only been a customer with this company for one month, but so far everything has been smooth. I appreciate the month-to-month contract option as it gives me flexibility. The monthly charges of $19.55 are reasonable. The only downside is that internet service is not included, but I was aware of that when I signed up. I prefer to pay by mailed check and have had no issues with the payment process. Overall, I am satisfied with my experience so far.
--------------------------------------------------------------------------------
Índice: 2641
Cliente: 6907-NZZIJ
Feedback: I have been a customer with this company for 36 months and unfortunately, I have decided to churn. The monthly charges of $99.15 for fiber optic internet service were reasonable, however, I found that the service was not consistently reliable. I paid using electronic check which was convenient, but ultimately I decided to switch to a different provider for a more stable connection.
--------------------------------------------------------------------------------
Índice: 2896
Cliente: 6023-GSSXW
Feedback: I have been a customer with this company for almost 6 years now and I have been very satisfied with the service. The monthly charges are reasonable at $61.45 and I appreciate the convenience of automatic credit card payments. The DSL internet service has been reliable and I have had no issues with connectivity. Overall, I have no complaints and would recommend this company to others.
--------------------------------------------------------------------------------
Índice: 2936
Cliente: 5688-KZTSN
Feedback: I recently cancelled my service with this provider after being a customer for 15 months on a month-to-month contract. I was paying $20 per month for internet service, but unfortunately, I did not have a good experience with the provider. The internet service was unreliable and I often experienced slow speeds and frequent outages. Additionally, the payment method of electronic check was not convenient for me as it often resulted in delays and issues with billing. Overall, I was not satisfied with the service and decided to switch to a different provider.
--------------------------------------------------------------------------------
Índice: 2959
Cliente: 7694-VLBWQ
Feedback: I have been a customer with this company for over five years now, consistently paying $104.1 per month for my fiber optic internet service. Despite being with them for so long, I unfortunately had to cancel my service due to moving to a new area that they do not cover. I have always paid through electronic check and never had any issues with billing. Overall, I have been satisfied with the service provided and would recommend them to others in the area.
--------------------------------------------------------------------------------
Índice: 3153
Cliente: 1619-YWUBB
Feedback: I have been a customer with this company for over 5 years now and I have been very satisfied with the service. The monthly charges are very reasonable at $24.95 and I appreciate the convenience of the automatic credit card payment method. Even though I do not have internet service with this company, I have never had any issues with my account or billing. Overall, I am a happy customer and have no plans to switch providers.
--------------------------------------------------------------------------------
Índice: 3300
Cliente: 9575-IWCAZ
Feedback: I have been a customer with this company for 6 months now and I have not experienced any issues with their service. I am on a one year contract with a monthly charge of $25.1 which I find to be reasonable. Even though I do not have internet service with this company, I have been satisfied with the payment method of mailing a check. Overall, I am happy with my experience so far and have no plans to switch providers.
--------------------------------------------------------------------------------
Índice: 3388
Cliente: 4702-HDRKD
Feedback: I have been a loyal customer of this DSL internet service provider for over five years now. The automatic bank transfer payment method makes it convenient for me to pay my monthly charges without any hassle. The monthly charges of $49.35 are reasonable for the quality of service I receive. I have had no issues with churn and am satisfied with the reliability of the internet connection. Overall, I am happy with my experience with this provider and would recommend it to others.
--------------------------------------------------------------------------------
Índice: 3476
Cliente: 6469-QJKZW
Feedback: I have been a customer with this company for 4 months now on a month-to-month contract. I do not have internet service with them, so my monthly charges are only $20.15. I appreciate the convenience of paying with electronic check. Overall, I have had a positive experience with this company and have not had any issues with their service. I am satisfied with the value for the price I am paying.
--------------------------------------------------------------------------------
Índice: 3515
Cliente: 2672-HUYVI
Feedback: I recently canceled my service after being a customer for 6 months. I was on a month-to-month contract with monthly charges of $91.1 for fiber optic internet service. I was satisfied with the speed and reliability of the internet connection, but ultimately decided to switch to a different provider offering a better promotional rate. The payment method of electronic check was convenient and I never had any issues with billing. Overall, I had a positive experience with the service but ultimately made the decision to leave due to cost considerations.
--------------------------------------------------------------------------------
Índice: 3837
Cliente: 3274-NSDWE
Feedback: I have been a loyal customer with this company for over 5 years now and have never experienced any issues with my service or billing. The automatic credit card payment method makes it convenient for me to pay my monthly charges on time. Even though I do not have internet service with this provider, I am satisfied with the overall service and have no plans to switch to another company. I would definitely recommend this company to others looking for reliable and affordable services.
--------------------------------------------------------------------------------
Índice: 4875
Cliente: 3348-CFRNX
Feedback: I recently made the difficult decision to cancel my service after being a customer for 28 months. While the fiber optic internet service was reliable and fast, the monthly charges of $92.35 became too expensive for me to justify. Additionally, having to mail in a check for payment was inconvenient compared to other payment methods available. I would have appreciated more affordable pricing options and more convenient payment methods to potentially have kept me as a customer.
--------------------------------------------------------------------------------
Índice: 5324
Cliente: 6614-VBEGU
Feedback: I have been a customer with this internet provider for 24 months now and I have been satisfied with the service. The monthly charges of $69.45 for DSL internet are reasonable and the automatic bank transfer payment method makes it convenient for me. I have not experienced any issues with the service and have not had any reason to consider switching providers. Overall, I am happy with my experience and would recommend this provider to others.
--------------------------------------------------------------------------------
Índice: 5328
Cliente: 1293-BSEUN
Feedback: I have been a customer with this company for 6 years now and I have been satisfied with the service overall. The monthly charges are very reasonable at $20.7 and I appreciate the option to pay by mailed check. However, I do wish that internet service was available as an option as it would make my experience even better. Overall, I have no complaints and I am happy to continue being a customer.
--------------------------------------------------------------------------------

In [170]:
# duração explícita no feedback
correcoes_tenure = {
    1059: 72,
    1791: 12,
    1984: 72,
    2372: 1,
    2641: 36,
    2936: 15,
    3300: 6,
    3476: 4,
    3515: 6,
    4875: 28,
    5324: 24,
    5328: 72
}

# em que o feedback não permite saber o tempo exato
indices_sem_tenure_exato = [
    1097, 2361, 2896, 2959, 3153, 3388, 3837
]

### 5.3. Correção dos valores

In [171]:
df_valores_tratados = df_bruto.copy()

In [172]:
# correções manuais para os valores conhecidos
for indice, meses in correcoes_tenure.items():
    df_valores_tratados.loc[indice, "tenure"] = str(meses) # str para evitar problemas de conversão, visto que a coluna original é do tipo str

# <NA> para os casos sem duração exata
df_valores_tratados.loc[indices_sem_tenure_exato, "tenure"] = pd.NA

# verificar
display(
    df_valores_tratados.loc[
        list(correcoes_tenure.keys()) + indices_sem_tenure_exato,
        ["customerID", "tenure"]
    ].sort_index()
)

print("Total de valores ausentes:", df_valores_tratados["tenure"].isna().sum())

      customerID tenure
1059  7301-ABVAD     72
1097  9651-GTSAQ    NaN
1791  0135-NMXAP     12
1984  3892-NXAZG     72
2361  3934-HXCFZ    NaN
2372  1622-HSHSF      1
2641  6907-NZZIJ     36
2896  6023-GSSXW    NaN
2936  5688-KZTSN     15
2959  7694-VLBWQ    NaN
3153  1619-YWUBB    NaN
3300  9575-IWCAZ      6
3388  4702-HDRKD    NaN
3476  6469-QJKZW      4
3515  2672-HUYVI      6
3837  3274-NSDWE    NaN
4875  3348-CFRNX     28
5324  6614-VBEGU     24
5328  1293-BSEUN     72

Total de valores ausentes: 7

## 6. Transformação de valores booleanos para valores categóricos na coluna **SeniorCitizen**

In [173]:
df_valores_tratados['SeniorCitizen'].head()

0    0
1    0
2    1
3    1
4    0
Name: SeniorCitizen, dtype: int64

In [174]:
df_valores_tratados['SeniorCitizen'] = df_valores_tratados['SeniorCitizen'].map({
    0: 'Não',
    1: 'Sim'
})

In [175]:
df_valores_tratados['SeniorCitizen'].head()

0    Não
1    Não
2    Sim
3    Sim
4    Não
Name: SeniorCitizen, dtype: str

## ?. Tratamento dos tipos de dados

In [176]:
df_tipagem = df_bruto.copy()

### ?.1 Identificação dos tipos corretos

In [177]:
df_bruto.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                  str
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
CustomerFeedback        str
MonthlyIncome         int64
dtype: object

| Coluna | Descrição | Tipo de dado |
|--------|-----------|--------------|
| customerID | ID do cliente | string |
| gender | Gênero | category |
| SeniorCitizen | Cidadão idoso | category |
| Partner | Parceiro(a) | category |
| Dependents | Dependentes | category |
| tenure | Tempo de permanência | int |
| PhoneService | Serviço telefônico | category |
| MultipleLines | Múltiplas linhas | category |
| InternetService | Serviço de internet | category |
| OnlineSecurity | Segurança online | category |
| OnlineBackup | Backup online | catgeory |
| DeviceProtection | Proteção de dispositivos | category |
| TechSupport | Suporte técnico | category |
| StreamingTV | TV por streaming | category |
| StreamingMovies | Filmes por streaming | category |
| Contract | Contrato | category |
| PaperlessBilling | Faturamento sem papel | category |
| PaymentMethod | Método de pagamento | category |
| MonthlyCharges | Cobranças mensais | float |
| TotalCharges | Cobranças totais	| float |
| Churn | Situação de Cancelamento | category |
| CustomerFeedback | Feedback do cliente | string |
| MonthlyIncome | Renda mensal | float

In [178]:
tipos_corretos = {
    "customerID": "string",
    "gender": "category",
    "SeniorCitizen": "category",
    "Partner": "category",
    "Dependents": "category",
    "tenure": "int",
    "PhoneService": "category",
    "MultipleLines": "category",
    "InternetService": "category",
    "OnlineSecurity": "category",
    "OnlineBackup": "category",
    "DeviceProtection": "category",
    "TechSupport": "category",
    "StreamingTV": "category",
    "StreamingMovies": "category",
    "Contract": "category",
    "PaperlessBilling": "category",
    "PaymentMethod": "category",
    "MonthlyCharges": "float",
    "TotalCharges": "float",
    "Churn": "category",
    "CustomerFeedback": "string",
    "MonthlyIncome": "float"
}

### ?.2. Correção dos tipos de dados

In [179]:
for coluna, tipo in tipos_corretos.items():
    df_tipagem[coluna] = df_tipagem[coluna].astype(tipo)

ValueError: invalid literal for int() with base 10: 'unknown'

In [ ]:
df_tipagem.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                  str
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
CustomerFeedback        str
MonthlyIncome         int64
dtype: object

## A fazer:

a coluna total charges tem muitos valores ausentes, como temos a associação com a coluna tenure, podemos criar uma regra para preencher os valores ausentes de total charges, multiplicando o valor de monthly charges pelo valor de tenure